[window]
world_dimensions={w=1920,h=1080,type="size"} #The size of the overall app space.
source_rectangle={x=0,y=0,w=1920,h=1080,type="rect"} #the rectangle of the world space to render.
destination_rectangle={x=0,y=0,w=0,h=0,type="rect"} #The output window size and position to render.
