
#TOML settings file thoughts. (in TOML!)

#headings create objects and below them key = value or key = [value,{metadata}]
#doing it bothways allows for a simpler settings file but also allows to give hints on
#conversions or visualization metadata. 
[engine]
project_path=["dsqt_development",{type="string", test="", restart="full"}]

[engine.window]
world_dimensions=[{w=1920,h=1080},{type="size"}] #The size of the overall app space.
source_rectangle=[{x=0,y=0,w=1920,h=1080},{type="rect"}] #the rectangle of the world space to render.
destination_rectangle=[{x=0,y=0,w=0,h=0},{type="rect"}] #The output window size and position to render.

[engine.examples]
#this is the same as example_simple = [450,{}] and should take the same code path
example_simple = 450 #simple example makes an int

example_full = ["450",{type="int",max=700,min=0,step=10,name="Example Full",desc="An example of a full value with meta data for a stepped slider"}]
example_string = "450" #simple format, will read as string, but you can convert to a number ofcourse

#an array. note the double brackets
example_array = [["fe","fi","fo","fum"]] 

#this is not valid as it conflicts with value as array pattern. 
#We could probably make this work by analyzing the content, but
#for simplicity sake I say we just don't allow it. 
example_array_bad = [{object="one"},{issue="nice"},"fo","fum"] 

#These should all produce a 100x100 rectangle with an x and y value at 10,5
example_rect_1 = {x=10,y=5,w=100,h=100} #will read as an object, but can try to convert to a rect
example_rect_2 = [[10,5,100,100]] #will read as a simple array, but can try to convert to a rect (or a color or vec4)
example_rect_3 = {x1=10,y1=5,x2=110,y2=105} #will read as an object, but can try to convert to a rect
example_rect_4 = [{x=10,y=5,w=100,h=100},{type="rect",x_min=0,x_max=500,y_min=0,y_max=500}] #the meta data is TBD

#colors
example_color_1 = {r=0.5,g=0.5,b=0.5,a=1.0}
example_color_2 = [{r=0.5,g=0.5,b=0.5,a=1.0},{type="color"}]
example_color_3 = [[0.5,0.5,0.5,1.0],{type="color"}]
example_color_4 = [[0.5,0.5,0.5],{type="color"}] 
