
#TOML settings file thoughts. (in TOML!)

#headings create objects and below them key = value or key = [value,{metadata}]
#doing it bothways allows for a simpler settings file but also allows to give hints on
#conversions or visualization metadata. 
[engine]
project_path=["dsqt_development",{type="string", test="", restart="full"}]

[engine.reload]
paths=[
{path="%APP%/data/", recurse=true},
{path="%APP%/qml/", recurse=true}
] #reload path to data



[engine.window]
world_dimensions=[{w=3840,h=2160},{type="size"}] #The size of the overall app space.
source={x=0,y=0,w=3840,h=2160} #the rectangle of the world space to render.
destination={x=0,y=0,w=1920,h=1080}#,{type="rect"}] #The output window size and position to render.

[engine.resource]
location="%LOCAL%/hpi1/"
resource_db="db.sqlite"

[engine.bridgesync]
#whether to use the local path to the shared path to find bridgesync.
launch_bridgesync=true
app_path="%SHARE%/bridgesync/bridge_sync_console.exe"

#unimplemented, but the idea is to allow these settings to live is seperate
#toml files
#use_settings_file=false
#settings_file="bridgesync.toml"

[engine.bridgesync.connection]
server = "http://localhost:7080"
#server = "https://app.hpi1.dev.bridge.downstream.com"
#auth_server = "https://hpi1-api-userpool.auth.us-east-2.amazoncognito.com"
#client_id = ""
#client_secret= ""
directory="%LOCAL%/hpi1/"
interval = 5
verbose = true

